#!/bin/bash
set -ev

GOOGLE_PLAY_SERVICE_ACCOUNT=Swooby\ Play\ Android\ Dev-159296a07371.json
FIREBASE_SERVICE_ACCOUNT=alfred-mobile-firebase-crashreporting-nlf98-ef1a85c614.json
SIGNING_KEYSTORE=android_alfred.jks
GOOGLE_SERVICES=app/google-services.json

tar cvf secrets.tar "$GOOGLE_SERVICES" "$GOOGLE_PLAY_SERVICE_ACCOUNT" "$FIREBASE_SERVICE_ACCOUNT" "$SIGNING_KEYSTORE"
travis encrypt-file secrets.tar -f
git add secrets.tar.enc