#!/bin/bash
set -e
#set -ev

if [ "$TRAVIS" != "true" ]; then
  pushd `dirname $0` > /dev/null
  SCRIPTPATH=`pwd`
  popd > /dev/null

  FirebaseServiceAccountFilePath=$SCRIPTPATH/../alfred-mobile-firebase-crashreporting-nlf98-ef1a85c614.json
fi

#echo FirebaseServiceAccountFilePath=$FirebaseServiceAccountFilePath
#ls -la $FirebaseServiceAccountFilePath

./gradlew :app:firebaseUploadReleaseProguardMapping -PFirebaseServiceAccountFilePath=${FirebaseServiceAccountFilePath} -PKEYSTORE=${KEYSTORE} -PKEYSTORE_PASSWORD=${KEYSTORE_PASSWORD} -PKEY_ALIAS=${KEY_ALIAS} -PKEY_PASSWORD=${KEY_PASSWORD}

#ls -la app/build/outputs/apk/

sudo -H easy_install --upgrade google-api-python-client
python ci/google_play_upload_apk.py --packageName=com.swooby.alfred --apkFilename=app/build/outputs/apk/swooby-android-app-alfred-release.apk

# TODO:(pv) Upload APK to GitHub
